services:
  client:
    container_name: client
    build: ./client
    tty: true
    volumes:
      - client:/home/client
    ports:
      - 3000:3000
    restart: always
    networks:
      - backend
    depends_on:
      - server

  server:
    container_name: server
    build: ./server
    restart: always
    volumes:
      - server:/home/server
    # this port is open just for experiment
    ports:
      - 8081:8081
    networks:
      - backend
      - database
    secrets:
      - key
      - cert
    depends_on:
      - database

  database:
    container_name: database
    build: ./database
    restart: always
    networks:
      - database

volumes:
  client:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./client
  server:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./server

networks:
  backend:
    driver: bridge
  database:
    driver: bridge

secrets:
  key:
    file: ./secrets/key.pem
  cert:
    file: ./secrets/cert.pem
